# Generated by Django 4.0.2 on 2022-02-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="user",
            name="lon",
        ),
        migrations.RemoveField(
            model_name="user",
            name="place_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
