# Generated by Django 4.0.2 on 2025-01-24 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.TextField(default='com.dept.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessgroup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
